version: "3"
services:
  app:
    container_name: awesome_nest_boilerplate
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./postgres_data:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
